# Generated by Django 4.2.3 on 2023-07-23 21:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_comentario_noticia_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='comentarios',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticias.noticia'),
        ),
    ]
