# Generated by Django 4.2.3 on 2023-07-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('noticias', '0002_rename_categorias_categoria_rename_noticias_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='noticias/notice_default.png', null=True, upload_to='noticias'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
