# Generated by Django 4.2.3 on 2023-07-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_remove_noticia_comentarios_alter_comentario_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
