# Generated by Django 4.2.3 on 2023-07-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nombre',)},
        ),
    ]
